name: Streamlit CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # # Step 4: Run tests (if you have tests)
    # - name: Run tests
    #   run: |
    #     pytest

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Build the Docker image
    - name: Build Docker image
      run: |
        docker build -t streamlit-app:latest .

    # Step 3: Deploy the Docker container
    - name: Deploy Streamlit App
      run: |
        docker run -d -p 8501:8501 --ipc="host" --name=product_guide streamlit-app:latest

    # Step 4: Clean up unused Docker images and containers
    - name: Clean previous images and containers
      run: |
        docker system prune -f
